window:
  padding:
    x: 10
  #  y: 0
  opacity: 0.95

font:
  normal:
    family: RobotoMono Nerd Font Mono
    style: Regular
  size: 12.0

# Colors (Nord)
colors:
  primary:
    background: "#2e3440"
    foreground: "#d8dee9"
    dim_foreground: "#a5abb6"
    #bright_foreground: '#eaeaea'

  cursor:
    text: "#2e3440"
    cursor: "#d8dee9"

  vi_mode_cursor:
    text: "#2e3440"
    cursor: "#d8dee9"

  search:
    matches:
      foreground: CellBackground
      background: "#88c0d0"
    #focused_match:
    #  foreground: '#ffffff'
    #  background: '#000000'

  normal:
    black: "#3b4252"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#88c0d0"
    white: "#e5e9f0"
  bright:
    black: "#4c566a"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#8fbcbb"
    white: "#eceff4"
  dim:
    black: "#373e4d"
    red: "#94545d"
    green: "#809575"
    yellow: "#b29e75"
    blue: "#68809a"
    magenta: "#8c738c"
    cyan: "#6d96a5"
    white: "#aeb3bb"

# Cursor settings
cursor:
  style:
    shape: Underline

  # Highlight window damage information.
  #highlight_damage: false
